from __future__ import annotations
from pathlib import Path

MODEL_NAME = "models/yolov8s.pt"

DEVICE_AUTO = True
DEVICE_PREFERENCE = "cuda"

CONF_THRES = 0.35
IOU_NMS_THRES = 0.50
PERSON_CLASS_ID = 0

USE_FULL_FRAME = True
ROI = [0, 0, 99999, 99999]
CROP_MARGIN = 0
SHOW_REGION_RECT = False

MIN_BOX_AREA = 1800
MAX_BOX_AREA = 999999999
MAX_ASPECT_RATIO = 4.2
MIN_SCORE_FOR_TRACK = 0.35

TRACK_MAX_AGE_FRAMES = 10
MIN_TRACK_FRAMES_TO_COUNT = 3
MATCH_IOU_WEIGHT = 0.50
MATCH_CENTER_WEIGHT = 0.20
MATCH_HIST_WEIGHT = 0.30
MIN_MATCH_SCORE = 0.35
CENTER_DIST_NORM = 220.0
DUPLICATE_IOU_THRES = 0.65
SUPPRESS_NEW_NEARBY_IOU = 0.35
MATURE_HITS = 4
REID_HIST_SIM_THRES = 0.82
REID_CENTER_DIST = 180.0
REID_MAX_GAP_FRAMES = 20

# Thesis definitions
VISIT_GAP_SECONDS = 5.0
USAGE_MIN_SECONDS = 15.0

WINDOW_SECONDS = 1.0

WINDOW_NAME = "People Counter - Hybrid Tracker"
FULLSCREEN = False
DRAW_TRACK_IDS = True
SHOW_LIVE_WINDOW = False
FONT_BIG = 1.0
THICK_BIG = 2

OUTPUT_DIR = Path("outputs")
ALLOWED_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv", ".m4v"}
